### ISSUE TITLE
Error trying to display a numpy array

### ISSUE THREAD

**Issue by martinRenou** [agoose77/numpy-html#1]
Hey @agoose77, I tried your package and had the following error:
![numpy_html](https://user-images.githubusercontent.com/21197331/51986437-89655e80-24a0-11e9-8f54-af7301318f1e.png)

I'm on Python 3.6, using numpy 1.15.4 and numpy_html 0.0.2

**Comment by agoose77** [comment]
Thanks for the report, I'll quickly take a look ...

**Comment by agoose77** [comment]
Fixed by https://github.com/agoose77/numpy-html/commit/af924a0e750c1a2d3beae11f037d16246c484e88

**Comment by martinRenou** [comment]
That was fast! Thanks :)
