### ISSUE TITLE
Adding to Ipython startup file for autoimport

### ISSUE THREAD

**Issue by csheaff** [agoose77/numpy-html#2]
Nice tool, thanks. I'm trying to automatically import this into Jupyter everytime I start a notebook via an Ipython startup file. However importing numpy_html only seems to work when manually importing it. Any tips? Here's what's in my start up file:

`c = get_config()
c.InteractiveShellApp.exec_lines = [
    'import matplotlib.pyplot as plt\n'
    'import pandas as pd\n'
    'import seaborn as sns\n'
    'import scipy.io as sio\n'
    'import numpy_html\n'
    'import numpy as np\n'
]`

**Comment by agoose77** [comment]
The display hook is automatically installed on import by testing whether `get_ipython()` is defined. You can manually call the hook yourself with `numpy_html.install_jupyter_hook()`, does this work? @csheaff (just in case it doesn't notify you by default!)

**Comment by csheaff** [comment]
Unfortunately no.

**Comment by agoose77** [comment]
Which file are you running this in? I've placed this in `~/.ipython/profile_default/ipython_config.py` and it works.

**Comment by csheaff** [comment]
Ahh, I was sticking it in a startup script in ~/.ipython/profile_default/startup. Now it works. Thanks!

**Comment by agoose77** [comment]
Awesome!
