### ISSUE TITLE
REAME.md doesn't seem to show the actual Python output functions used

### ISSUE THREAD

**Issue by texadactyl** [agoose77/numpy-html#4]
Works just fine in Jupyter as stated.  But, it would be nice if the example was amended to show the print/plot/whatever statements for non-Jupyter usage as well as Jupyter.

It turns out, Spyder is also a popular editor/debugger in use in addition to command line execution for batch-oriented Python scripts.

Also, it would be nice for consistency in Anaconda (also gaining popularity) if numpy-html was made part of Anaconda.  Personally, I do not mind the `pip` exception but there are a lot of part-time Python programmers who are actually Scientists.  Your call.

**Comment by agoose77** [comment]
Hi @texadactyl,

This tool depends upon IPython, as it uses the rich display hook functionality. In particular, it uses the HTML rendering, which only works in the Notebook / Jupyter Lab Console.

I'm a scientist myself, and prefer to use `pip`, but indeed, I've seen that increasingly people are being told to "just use anaconda". I'd be happy for this tool to be included with numpy / IPython, but I'd need to consult the relevant people, and go through a review process first.

I'm going to close this issue, as I don't think there is anything that I can action here, but feel free to open it if you feel there are unanswered issues. Thank you for trying out the tool!

**Comment by texadactyl** [comment]
Okay, I just read your ```__init__.py``` code.  What I asked for might be a big deal since this seems only intended for Jupyter.  It would require clever use of .format in other cases.

Anaconda: Yes, using `pip` is probably fine.  Agreed.

The tool is nice.  I'd love to have the HTML rich output to an object that could be saved as an HTML file, much the same way plots can be saved as PNGs.  That is a lot of work.  You're a Scientist?  You probably have more pressing things to do!

**Comment by agoose77** [comment]
@texadactyl you can run `numpy_html.array_to_html(array)` to produce an HTML string, which you can then save to an image. This won't include the funky styling that Jupyter adds to HTML tables, but the CSS for that is quite straightforward, and you'd just need to prepend it to the string inside a `<style>` element

**Comment by texadactyl** [comment]
Thanks. Yes, 
```
<table style='border-style:solid;border-width:1px;'>
<tr>
<td style='font-family:monospace;white-space: pre;' title='(0, 0)'>0 </td>
<td style='font-family:monospace;white-space: pre;' title='(0, 1)'>1 </td>
<td><center>⋯</center></td>
<td style='font-family:monospace;white-space: pre;' title='(0, 5)'>5 </td>
<td style='font-family:monospace;white-space: pre;' title='(0, 6)'>6 </td>
</tr>
<tr>
<td style='font-family:monospace;white-space: pre;' title='(1, 0)'>7 </td>
<td style='font-family:monospace;white-space: pre;' title='(1, 1)'>8 </td>
<td><center>⋯</center></td>
<td style='font-family:monospace;white-space: pre;' title='(1, 5)'>12</td>
<td style='font-family:monospace;white-space: pre;' title='(1, 6)'>13</td>
</tr>
<tr>
<td><center>⋮</center></td>
<td><center>⋮</center></td>
<td><center>⋱</center></td>
<td><center>⋮</center></td>
<td><center>⋮</center></td>
</tr>
<tr>
<td style='font-family:monospace;white-space: pre;' title='(5, 0)'>35</td>
<td style='font-family:monospace;white-space: pre;' title='(5, 1)'>36</td>
<td><center>⋯</center></td>
<td style='font-family:monospace;white-space: pre;' title='(5, 5)'>40</td>
<td style='font-family:monospace;white-space: pre;' title='(5, 6)'>41</td>
</tr>
<tr>
<td style='font-family:monospace;white-space: pre;' title='(6, 0)'>42</td>
<td style='font-family:monospace;white-space: pre;' title='(6, 1)'>43</td>
<td><center>⋯</center></td>
<td style='font-family:monospace;white-space: pre;' title='(6, 5)'>47</td>
<td style='font-family:monospace;white-space: pre;' title='(6, 6)'>48</td>
</tr>
</table>
```
Don't start any out-of-control chain reactions!  (=:
