### ISSUE TITLE
Error with pip installation

### ISSUE THREAD

**Issue by stared** [agoose77/numpy-html#5]
I try to install using `pip install numpy-html`, but I get:

```
Collecting numpy-html
  Could not find a version that satisfies the requirement numpy-html (from versions: )
No matching distribution found for numpy-html
```

My settings:

* macOS High Sierra (10.13.6)
* pip 19.0.3
* Python 3.5

Apparently, it exists on http://pypi.org/project/numpy-html.

**Comment by agoose77** [comment]
I didn't see this until just now, apologies. I suspect this is related to an out-of-date Pip cache. If you tried this again today, I'd expect it to work.
